### ISSUE TITLE
linux-odroid-n2-57 compile error on crypto/aegis128-neon-inner.c

### ISSUE THREAD

**Issue by astralaster** [archdroid-org/pkgbuilds#1]
Hi,

Ive tried to compile your linux-odroid-n2-57 PKGBUILD and it failed with an compilation error:

`crypto/aegis128-neon-inner.c: In function 'crypto_aegis128_init_neon':
crypto/aegis128-neon-inner.c:151:3: error: incompatible types when initializing type 'unsigned char' using type 'uint8x16_t'
  151 |   k ^ vld1q_u8(const0),
      |   ^
crypto/aegis128-neon-inner.c:152:3: error: incompatible types when initializing type 'unsigned char' using type 'uint8x16_t'
  152 |   k ^ vld1q_u8(const1),
      |   ^
crypto/aegis128-neon-inner.c:147:29: warning: missing braces around initializer [-Wmissing-braces]
  147 |  struct aegis128_state st = {{
      |                             ^
......
  151 |   k ^ vld1q_u8(const0),
      |   {
  152 |   k ^ vld1q_u8(const1),
  153 |  }};
      |  }`

I think its a problem with gcc 10: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96377

**Comment by jgmdev** [comment]
Last time that I compiled it worked, but as you found out it does seems to be an issue with latest GCC. A user posted a patch to fix the issue on the [odroid forum](https://forum.odroid.com/viewtopic.php?p=307363#p307363) for the 5.8 kernel which may also work on 5.7. Also disabling AEGIS support should get it compiling, not sure how beneficial that crypto module is.

I will give the patch a test run later and include it on the repo.

**Comment by astralaster** [comment]
Yes harddroid is me. :) Maybe I should fork your repo and supply pull requests?

**Comment by jgmdev** [comment]
ahh I see hehe! you are welcome :smiley:
